services:
  mysql:
    image: "mysql:${MYSQL_VERSION:-5.7}"
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - psnetwork
    volumes:
      - ./docker/db:/var/lib/mysql
  prestashop:
    image: "prestashop/prestashop:${PRESTASHOP_VERSION:-latest}"
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "${PRESTASHOP_PORT:-8080}:80"
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    networks:
      - psnetwork
    volumes:
      # Recommended when developing modules only
      # or working by attaching vscode directly to container.
      # - psdata:/var/www/html

      # To work with PrestaShop files directly on the host, first complete the PrestaShop installation.
      # Then, copy PrestaShop files from container (container:/var/www/html)
      # to root (.) location, stop containers and uncomment the bind mount below:
      - .:/var/www/html

networks:
  psnetwork:

  # Used by default for persistent PrestaShop files.
  # Comment this out if switching to a bind mount (e.g., `.:/var/www/html`) for direct file access.
  # psdata:
